### ISSUE TITLE
npm run dev ERROR

### ISSUE THREAD

**Issue by ifibercc** [wangdahoo/vonic-template#1]
![image](https://cloud.githubusercontent.com/assets/13199426/20637929/8adb4ece-b3d1-11e6-8103-bfd5e3c0ab1e.png)

下载下来之后，cnpm install ，然后run dev会有如下报错
win 10
node v4.5.0
npm 2.15.9

**Comment by wangdahoo** [comment]
很早的版本了，现在应该没有这个问题了。
